
import { VocabularyItem, SentenceItem } from './types';

export const VOCABULARY: Record<string, VocabularyItem[]> = {
  "Body Parts & Appearance": [
    { character: "下巴", pinyin: "xiàba", translation: "chin" },
    { character: "脸", pinyin: "liǎn", translation: "face" },
    { character: "耳朵", pinyin: "ěrduo", translation: "ear" },
    { character: "头", pinyin: "tóu", translation: "head" },
    { character: "头发", pinyin: "tóufà", translation: "hair" },
    { character: "眼睛", pinyin: "yǎnjīng", translation: "eyes" },
    { character: "鼻子", pinyin: "bízi", translation: "nose" },
    { character: "嘴巴", pinyin: "zuǐbā", translation: "mouth" },
    { character: "牙", pinyin: "yá", translation: "teeth" },
    { character: "舌头", pinyin: "shétou", translation: "tongue" },
    { character: "皮肤", pinyin: "pífū", translation: "skin" },
    { character: "肚子", pinyin: "dǔzi", translation: "tummy" },
    { character: "脚", pinyin: "jiǎo", translation: "feet" },
    { character: "手指头", pinyin: "shǒuzhǐtou", translation: "fingers" },
    { character: "手", pinyin: "shǒu", translation: "hand" },
    { character: "身高", pinyin: "shēngāo", translation: "height" },
    { character: "体重", pinyin: "tǐzhòng", translation: "weight" },
    { character: "长相", pinyin: "zhǎngxiàng", translation: "appearance" },
    { character: "眼镜", pinyin: "yǎnjìng", translation: "glasses" },
    { character: "卷发", pinyin: "juǎnfà", translation: "curly hair" },
    { character: "直发", pinyin: "zhífà", translation: "straight hair" },
    { character: "大眼睛", pinyin: "dà yǎnjīng", translation: "big eyes" },
    { character: "小嘴巴", pinyin: "xiǎo zuǐbā", translation: "small mouth" },
    { character: "高鼻子", pinyin: "gāo bízi", translation: "high nose" },
    { character: "不胖也不瘦", pinyin: "bù pàng yě bù shòu", translation: "neither fat nor thin" },
    { character: "又矮又胖", pinyin: "yòu ǎi yòu pàng", translation: "short and fat" },
    { character: "高", pinyin: "gāo", translation: "tall" },
    { character: "尖", pinyin: "jiān", translation: "pointy" },
    { character: "胖", pinyin: "pàng", translation: "fat" },
    { character: "瘦", pinyin: "shòu", translation: "thin" },
    { character: "矮", pinyin: "ǎi", translation: "short" },
    { character: "长得像", pinyin: "zhǎng de xiàng", translation: "look like" },
    { character: "漂亮", pinyin: "piàoliang", translation: "pretty" },
    { character: "可爱", pinyin: "kěài", translation: "cute" },
    { character: "难看", pinyin: "nánkàn", translation: "ugly" },
    { character: "圆", pinyin: "yuán", translation: "round" }
  ],
  "Food, Drinks & Currency": [
    { character: "吃", pinyin: "chī", translation: "eat" },
    { character: "喝", pinyin: "hē", translation: "drink" },
    { character: "喝水", pinyin: "hēshuǐ", translation: "drink water" },
    { character: "菜", pinyin: "cài", translation: "vegetables/dishes" },
    { character: "鱼", pinyin: "yú", translation: "fish" },
    { character: "虾", pinyin: "xiā", translation: "prawn" },
    { character: "牛肉", pinyin: "niúròu", translation: "beef" },
    { character: "鸡肉", pinyin: "jīròu", translation: "chicken" },
    { character: "猪肉", pinyin: "zhūròu", translation: "pork" },
    { character: "鱼肉", pinyin: "yúròu", translation: "fish (meat)" },
    { character: "面包", pinyin: "miànbāo", translation: "bread" },
    { character: "黄油", pinyin: "huángyóu", translation: "butter" },
    { character: "果酱", pinyin: "guǒjiàng", translation: "jam" },
    { character: "包子", pinyin: "bāozi", translation: "steamed bun" },
    { character: "油条", pinyin: "yóutiáo", translation: "fried dough stick" },
    { character: "豆浆", pinyin: "dòujiāng", translation: "soy milk" },
    { character: "饺子", pinyin: "jiǎozi", translation: "dumplings" },
    { character: "咖啡", pinyin: "kāfēi", translation: "coffee" },
    { character: "茶", pinyin: "chá", translation: "tea" },
    { character: "果汁", pinyin: "guǒzhī", translation: "juice" },
    { character: "牛奶", pinyin: "niúnǎi", translation: "milk" },
    { character: "粥", pinyin: "zhōu", translation: "porridge" },
    { character: "点心", pinyin: "diǎnxīn", translation: "snacks/desserts" },
    { character: "水果", pinyin: "shuǐguǒ", translation: "fruit" },
    { character: "中式", pinyin: "zhōngshì", translation: "Chinese style" },
    { character: "西式", pinyin: "xīshì", translation: "Western style" },
    { character: "中餐", pinyin: "zhōngcān", translation: "Chinese meal" },
    { character: "西餐", pinyin: "xīcān", translation: "Western meal" },
    { character: "早饭", pinyin: "zǎofàn", translation: "breakfast" },
    { character: "晚饭", pinyin: "wǎnfàn", translation: "dinner" },
    { character: "人民币", pinyin: "rénmínbì", translation: "RMB" },
    { character: "元", pinyin: "yuán", translation: "yuan" },
    { character: "澳元", pinyin: "àoyuán", translation: "AU dollar" },
    { character: "美元", pinyin: "měiyuán", translation: "US dollar" },
    { character: "角", pinyin: "jiǎo", translation: "jiao" },
    { character: "分", pinyin: "fēn", translation: "fen" },
    { character: "多少钱", pinyin: "duōshǎo qián", translation: "how much money" },
    { character: "贵", pinyin: "guì", translation: "expensive" },
    { character: "便宜", pinyin: "piányi", translation: "cheap" },
    { character: "通常", pinyin: "tōngcháng", translation: "usually" },
    { character: "还是", pinyin: "háishì", translation: "or" }
  ],
  "Illness & Health": [
    { character: "病", pinyin: "bìng", translation: "illness" },
    { character: "病人", pinyin: "bìngrén", translation: "patient" },
    { character: "嗓子", pinyin: "sǎngzi", translation: "throat" },
    { character: "咳嗽", pinyin: "késou", translation: "cough" },
    { character: "发烧", pinyin: "fāshāo", translation: "fever" },
    { character: "感冒", pinyin: "gǎnmào", translation: "cold" },
    { character: "力气", pinyin: "lìqi", translation: "strength" },
    { character: "体温", pinyin: "tǐwēn", translation: "body temperature" },
    { character: "度", pinyin: "dù", translation: "degree" },
    { character: "病假条", pinyin: "bìngjiàtiáo", translation: "sick leave note" },
    { character: "一张病假条", pinyin: "yì zhāng bìngjiàtiáo", translation: "a sick leave note" },
    { character: "全身", pinyin: "quánshēn", translation: "whole body" },
    { character: "生病", pinyin: "shēngbìng", translation: "get sick" },
    { character: "住院", pinyin: "zhùyuàn", translation: "be hospitalized" },
    { character: "发现", pinyin: "fāxiàn", translation: "discover" },
    { character: "看医生", pinyin: "kàn yīshēng", translation: "see a doctor" },
    { character: "开药", pinyin: "kāiyào", translation: "prescribe medicine" },
    { character: "拉肚子", pinyin: "lādùzi", translation: "have diarrhea" },
    { character: "休息", pinyin: "xiūxi", translation: "rest" },
    { character: "量体温", pinyin: "liáng tǐwēn", translation: "measure body temperature" },
    { character: "吃止疼药", pinyin: "chī zhǐténgyào", translation: "take painkillers" },
    { character: "吃止咳药", pinyin: "chī zhǐkéyào", translation: "take cough medicine" },
    { character: "吃退烧药", pinyin: "chī tuìshāoyào", translation: "take fever medicine" },
    { character: "多喝水", pinyin: "duō hē shuǐ", translation: "drink more water" },
    { character: "多休息", pinyin: "duō xiūxi", translation: "rest more" },
    { character: "不舒服", pinyin: "bù shūfu", translation: "uncomfortable" },
    { character: "痛", pinyin: "tòng", translation: "painful" },
    { character: "头痛", pinyin: "tóutòng", translation: "headache" },
    { character: "嗓子疼", pinyin: "sǎngzi téng", translation: "sore throat" },
    { character: "肚子疼", pinyin: "dùzi téng", translation: "stomachache" },
    { character: "牙疼", pinyin: "yáténg", translation: "toothache" },
    { character: "疼", pinyin: "téng", translation: "sore" },
    { character: "严重", pinyin: "yánzhòng", translation: "severe" },
    { character: "发冷", pinyin: "fālěng", translation: "chills" }
  ],
  "Key Verbs": [
      { character: "要", pinyin: "yào", translation: "want / need / going to" },
      { character: "让", pinyin: "ràng", translation: "let / make / ask someone to" },
      { character: "应该", pinyin: "yīnggāi", translation: "should" }
  ]
};

export const SENTENCES: Record<string, SentenceItem[]> = {
    "Body Parts & Appearance": [
        { character: "我有大眼睛。", pinyin: "Wǒ yǒu dà yǎnjīng", translation: "I have big eyes." },
        { character: "她的头发是卷发。", pinyin: "Tā de tóufà shì juǎnfà", translation: "Her hair is curly." },
        { character: "我的鼻子很高。", pinyin: "Wǒ de bízi hěn gāo", translation: "My nose is high." },
        { character: "他不胖也不瘦。", pinyin: "Tā bù pàng yě bù shòu", translation: "He is neither fat nor thin." },
        { character: "我戴眼镜。", pinyin: "Wǒ dài yǎnjìng", translation: "I wear glasses." }
    ],
    "Food, Drinks & Currency": [
        { character: "我喜欢吃包子。", pinyin: "Wǒ xǐhuān chī bāozi", translation: "I like eating steamed buns." },
        { character: "她每天喝豆浆。", pinyin: "Tā měitiān hē dòujiāng", translation: "She drinks soy milk every day." },
        { character: "我早饭吃面包。", pinyin: "Wǒ zǎofàn chī miànbāo", translation: "I eat bread for breakfast." },
        { character: "我不喜欢喝咖啡。", pinyin: "Wǒ bù xǐhuān hē kāfēi", translation: "I don’t like drinking coffee." },
        { character: "这个三元五角六分。", pinyin: "Zhège sān yuán wǔ jiǎo liù fēn", translation: "This is ¥3.56." },
        { character: "多少钱？", pinyin: "Duōshǎo qián", translation: "How much money?" },
        { character: "太贵了！", pinyin: "Tài guì le", translation: "Too expensive!" }
    ],
    "Illness & Health": [
        { character: "我生病了。", pinyin: "Wǒ shēngbìng le", translation: "I am sick." },
        { character: "我的嗓子疼。", pinyin: "Wǒ de sǎngzi téng", translation: "My throat hurts." },
        { character: "医生让我休息。", pinyin: "Yīshēng ràng wǒ xiūxi", translation: "The doctor told me to rest." },
        { character: "我应该多喝水。", pinyin: "Wǒ yīnggāi duō hē shuǐ", translation: "I should drink more water." },
        { character: "我要去看医生。", pinyin: "Wǒ yào qù kàn yīshēng", translation: "I’m going to see a doctor." }
    ],
    "Key Verbs": [
        { character: "我要去看医生。", pinyin: "wǒ yào qù kàn yīshēng", translation: "I’m going to see a doctor." },
        { character: "医生让我在家休息两天。", pinyin: "yīshēng ràng wǒ zài jiā xiūxi liǎng tiān", translation: "The doctor told me to rest at home for two days." },
        { character: "你应该多休息。", pinyin: "nǐ yīnggāi duō xiūxi", translation: "You should rest more." }
    ]
};
